"""create school table

Revision ID: 2bce8d22df62
Revises: 
Create Date: 2026-09-21 12:47:50.293914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import os
import json

# revision identifiers, used by Alembic.
revision: str = '2bce8d22df62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(
        geometry_type='POINT',
        srid=4326, dimension=2,
        spatial_index=False,
        from_text='ST_GeomFromEWKT',
        name='geometry',
        nullable=False
        ), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    school_table = sa.table('school',
        sa.Column('name', sa.String),
        sa.Column('address', sa.String),
        sa.Column('type', sa.String),
        sa.Column('geom', geoalchemy2.types.Geometry)
    )

    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    json_path = os.path.join(project_root, 'schools_extracted.json')

    if os.path.exists(json_path):
        with open(json_path, 'r', encoding='utf-8') as f:
            raw_data = json.load(f)

        prepared_data = []
        for item in raw_data:
            coords = item.get('coordinates')
            if isinstance(coords, (list, tuple)) and len(coords) == 2:
                lon, lat = coords[0], coords[1]
                wkt_geom = f'SRID=4326;POINT({lon} {lat})'

                prepared_data.append({
                    'name': item.get('FullName'),
                    'address': item.get('Address'),
                    'type': item.get('OrgType'),
                    'geom': wkt_geom
                })

        if prepared_data:
            op.bulk_insert(school_table, prepared_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
